### PR TITLE
Pipeline repair: Add function graspy.embed.MultipleASE.transform & add get_score to get score matrices

### PR DESCRIPTION
**Pull request by QuasiLegendre**

### CODE REVIEW

**Comment by j1c** [comment]
@QuasiLegendre @tathey1 Can someone tell me what is happening in this PR?

**Comment by bdpedigo** [comment]
I am going to close this pull request because I don't think this code is ready to be merged. Some of what you are changing here are major design decisions for the package that we would need to talk about more. You are more than welcome to keep working on your branch, however. A few comments though: 
  - Do not change the base classes extensively without talking to me and Jaewon (if you have the intention of getting things merged), you will likely break a lot of things unintentionally. You are more than welcome to override methods in the base class if you need to, however. 
  - I wouldn't call this a classifier, it's just one step in your pipeline 
  - There is no need for a `get_latent` method, you can just to `estimator.latent_left_`
  - Make sure you follow all of the instructions in the contributing guidelines before PRing code

**Comment by QuasiLegendre** [comment]
Fine, thanks.

**Comment by QuasiLegendre** [comment]
I will be careful next time.

**Pull request closed without merging**
