### PR TITLE
ASE with one substantive test 

### PR DESCRIPTION
**Pull request by bdpedigo**
Based on [this test from R package](https://github.com/neurodata/graphstats/blob/master/tests/testthat/test-ase.R), wrote similar test for ASE and looks like it's working. Still want to write more tests

### CODE REVIEW

**Comment by ebridge2** [comment]
+ explicitly do not specify `k` as a command line argument in your ase implementation. The base-class takes care of all kwargs and such; if you specify `k` as an explicit argument, you won't be able to use the flexibility of being able to hot-swap dimensionality reduction algorithms.
+ I think calling things "Embedders" sounds weird; especially for ASE and LSE where the E stands for embedding. I would call it AdjacencySpectralEmbedding or something like that if you want to be more descriptive, or AdjacencySpectralEmbed or something like that.

**Comment by j1c** [comment]
- I agree to AdjacencySpectralEmbed.
- ASE need more documentation. One for the class and one for the fit function.

**Comment by ebridge2** [comment]
@bdpedigo your tests are random. This means that they could (note, with low probability, but COULD) arbitrarily fail. Add a seed before the for-loop so that the outcome of the test is deterministic. Also, if you note in the R code, the tests there construct a simple hypothesis test. I would add hypothesis testing instead of simply doing binary testing like you do.

**Comment by bdpedigo** [comment]
hopefully most recent commit addresses those concerns @ebridge2?

**Comment by ebridge2** [comment]
seems fine; im checking your updated PR now. closing this one since you seem to say you want that branch to be integrated

**Pull request closed without merging**
