### PR TITLE
clear notebook output for inference tutorials

### PR DESCRIPTION
**Pull request by bdpedigo**
#### What does this implement/fix? Explain your changes.
Jupyter notebooks in docs should be uploaded with all cells un-run, so that sphinx will automatically build them with the current graspy version.

### CODE REVIEW

**Comment by alyakin314** [comment]
curious for future work: does this mean one have to clear them every PR that changes something that affects a tutorial? or they just need to be created cleared once?

**Comment by j1c** [comment]
> curious for future work: does this mean one have to clear them every PR that changes something that affects a tutorial? or they just need to be created cleared once?

When you push a notebook, it shouldn't have outputs since netlify will run it on their server and serve the users with the outputs netlify creates. Its a check to make sure notebook work as expected, and seems like there are bugs in this notebook?

**Comment by alyakin314** [comment]
> > curious for future work: does this mean one have to clear them every PR that changes something that affects a tutorial? or they just need to be created cleared once?
> 
> When you push a notebook, it shouldn't have outputs since netlify will run it on their server and serve the users with the outputs netlify creates. Its a check to make sure notebook work as expected, 

right, my question was: if i change the code that the notebook uses, do i have to go in and clear it again?

> and seems like there are bugs in this notebook?

that's not fun. will take a look in a moment.

**Comment by j1c** [comment]
> right, my question was: if i change the code that the notebook uses, do i have to go in and clear it again?

No.

**Comment by alyakin314** [comment]
should be gtg now

**Comment by bdpedigo** [comment]
`11:16:22 AM: TimeoutError in tutorials/inference/latent_distribution_test.ipynb:
11:16:22 AM: Cell execution timed out
11:16:22 AM: make: *** [html] Error 2`

new error, notebook takes too long it seems?

**Comment by alyakin314** [comment]
takes less than 2 minutes end to end on my humble potato

**Comment by alyakin314** [comment]
but i can tune down number or permutations

**Comment by alyakin314** [comment]
will do that, unless you have a way of extending the time to timeout

**Comment by bdpedigo** [comment]
Yeah, could you give that a try? Thx

**Comment by alyakin314** [comment]
interesting that we didn't have this when we merged #221

**Comment by alyakin314** [comment]
9:31:38 PM: Notebook error:
9:31:38 PM: TimeoutError in tutorials/inference/latent_position_test.ipynb:
9:31:38 PM: Cell execution timed out
9:31:38 PM: make: *** [html] Error 2

**Comment by alyakin314** [comment]
@j1c @bdpedigo decrease semipar iterations? this really feels like an issue elsewhere, but im not sure how to trace it.

**Comment by bdpedigo** [comment]
> @j1c @bdpedigo decrease semipar iterations? this really feels like an issue elsewhere, but im not sure how to trace it.

Not sure, it's possible that netlify is capping the total build time for everything, and it just happens to fail there. I'll just try making them smaller

**Comment by alyakin314** [comment]
@bdpedigo you should revert the latent distribution notebook to the one i had because i fixed a bug in it

**Comment by bdpedigo** [comment]
@alyakin314  all good?

**Comment by alyakin314** [comment]
doesn't seem like it..

**Comment by bdpedigo** [comment]
im not sure what you mean. i was asking if i reverted adequately. did you think tests should have passed on your version?

**Comment by bdpedigo** [comment]
i thought you meant you had uncommitted changes, and i thought my changes reflected yours above, so now im confused

**Comment by alyakin314** [comment]
@bdpedigo 
okay, i think this should work. 

if you care to understand what happened, here is my inductive thinking explanation:
1. you commited b40a14eb4048cdb4a9549542622d4d78cd915924 which cleared the notebooks. let's call the code in the ldt notebook at this point v1.0 for convenience. you likely did not shutdown the kernel here.
2. there was a bug in the ldt notebook associated with the inference api change. i fixed it. let's call this version of the ldt notebook v2.0. (commit 39a0d92c4c30201ff0ef4099ec76edbb0b0b805c )
3. the notebook now runs, but netlify times out. i decrease the number of the number of permutations to a smaller one. let's call this version v2.0 (- stands for less permutations). (commit a18aa87352073871b4bfce0240d621f5e7ab7742)
4. the notebooks still time out. you try to change them. i presume that you pulled my code and tried to decrease the number of iterations/graph size further down. but since your kernel was still running from step 1, or because you spinned it up before you pulled. the ldt notebook in your memory was still v1.0, as opposed to v2.0- on the disk. so when you overwrote what was on the disk instead of creating v2.0--, you created v1.0-- with the inference bug still there. (commit d47d0fbd925b24218a7e01145741e9ebfde4fe0a)
5. i offered you do undo it via 
```
git reset --hard a18aa87352073871b4bfce0240d621f5e7ab7742
git push --force
```
this would completely erase the last commit (d47d0fbd925b24218a7e01145741e9ebfde4fe0a) from the tree, and return the ldt to notebook to v2.0-. then you could proceed with adding your changes to lpt test. simplest way of doing that would be to store the lpt notebook elsewhere before reset-pushing.
6. i'm not entirely sure how you created ac0a9b1cc369da165127c31ce49aa4b6c3f1e37f , but i assume that you just undeed your changes by hand (ones i call --). but since the underlying notebook is still v1.0, the inference bug is still there.
7. i just took your last notebook and fixed the bug one more time by hand.

**Comment by alyakin314** [comment]
i just read through the text of the notebook it makes absolutely no sense. it's actually plain wrong.

**Comment by alyakin314** [comment]
not a proper fix of #177 , but now we at leas runs the test on the actual graphs we claims to be running on, and we don't postulate the wrong null hypothesis in the latex

**Comment by alyakin314** [comment]
@bdpedigo @j1c merge this whenever you are happy with it.

**Comment by bdpedigo** [comment]
@alyakin314 yes you're right, i used `git revert` (I usually prefer this since it's safer, harder to break something accidentally. Unless there's something that really shouldn't be in commit history, like committing sensitive info). But you're correct, I just reverted the wrong commit. Thanks for fixing

**Pull request merged**
