### PR TITLE
Tutorial notebooks clustering

### PR DESCRIPTION
**Pull request by caseypw**
#### What does this implement/fix? Explain your changes.
Adds tutorial notebook for all of the clustering functions

### CODE REVIEW

**Comment by caseypw** [comment]
Not sure why there are errors on files I did not change @bdpedigo @j1c

**Comment by bdpedigo** [comment]
@caseypw there are no errors in other files, those are just warnings. the error is 
> 11:50:46 PM: NoSuchKernel in tutorials/clustering/Cluster.ipynb:
11:50:46 PM: No such kernel named python37664bit685ec07b3663401c8f9febe9ed77e09a

somehow you changed the kernelspec of the notebook you added. need to update here 
https://github.com/neurodata/graspy/blob/76e008d04b8b0fe9f3e7f87b7a01f6f4274808bb/docs/tutorials/clustering/Cluster.ipynb#L244

**Comment by bdpedigo** [comment]
> @caseypw there are no errors in other files, those are just warnings. the error is
> 
> > 11:50:46 PM: NoSuchKernel in tutorials/clustering/Cluster.ipynb:
> > 11:50:46 PM: No such kernel named python37664bit685ec07b3663401c8f9febe9ed77e09a
> 
> somehow you changed the kernelspec of the notebook you added. need to update here
> https://github.com/neurodata/graspy/blob/76e008d04b8b0fe9f3e7f87b7a01f6f4274808bb/docs/tutorials/clustering/Cluster.ipynb#L244

@caseypw don't believe this was ever addressed so the documentation is not building. if we want to merge this, need to clear the custom kernelspec in your notebook

**Comment by bdpedigo** [comment]
also, note that the notebook needs to be empty (no cells have been run). And at a glance, looks like you are pulling in synthetic data from a file. a tutorial like this should just sample the data in the notebook. 

@caseypw closing this for now since hasn't been activity on it, but willing to reopen if you're interested in making these fixes

**Pull request closed without merging**
