### PR TITLE
Added subgraph to docs, added tutorial notebook (Addresses #305)

### PR DESCRIPTION
**Pull request by gkang7**
#### Reference Issues/PRs

Addresses #305 

#### What does this implement/fix? Explain your changes.

Updated files so that documentation for subgraph will actually show up on the build, and added a tutorial notebook for the coherent and incoherent algorithms (https://arxiv.org/pdf/1108.1427.pdf)

### CODE REVIEW

**Comment by j1c** [comment]
Can you clear outputs of your tutorial notebook?

**Comment by bdpedigo** [comment]
@j1c have any further comments on this one? I haven't reviewed

**Comment by bdpedigo** [comment]
@j1c any more thoughts? would like to merge or close or delegate

**Comment by j1c** [comment]
This is good to merge. Fixed conflicts.

**Review by j1c — APPROVED** [review]

**Comment by pauladkisson** [comment]
@j1c @bdpedigo, there is an extra space in the title line of docs/reference/subgraph.rst, and it's throwing a warning in the doc build.  I must not have pulled my upstream remote after this got merged, so I didn't catch it before.

**Comment by bdpedigo** [comment]
@pauladkisson make an issue or PR?

**Pull request merged**
