### PR TITLE
create align module

### LINKED ISSUE #367: create an align module
create an align module, which should include at least the following:

- [x] sign flips (currently used in the latent distribution test)
- [x] regular procrustes
- [ ] modified matched procrustes (currently used in the latent position test)
- [x] unmatched ('seedless') procrustes (currently in R code in Agterberg's github and in python on my old brunch)-

### PR DESCRIPTION
**Pull request by alyakin314**
#### Reference Issues/PRs
Fixes #367 

#### What does this implement/fix? Explain your changes.
WIP

#### Any other comments?
WIP

### CODE REVIEW

**Comment by alyakin314** [comment]
@bdpedigo @j1c 
not a major issue, but just pointing out that here there were no rebases and github diff shows up fine, but codev still shows many files in diff that shouldnt be there. not sure what's up with that commit/pr that it acts so weirdly everywhere else.

**Comment by alyakin314** [comment]
(self-notes)

today:
- graspy/align/base.py done
- graspy/align/sign_flips.py done
- tests/test_sign_flips.py done
- graspy/align/procrustes.py created; coherent with base.py; runs but untested
- tests/test_seedless_prcrustes created; unpopulated for the most part.

tomorrow:
- graspy/align/procrustes.py
- tests/test_procrustes.py
- rest if time permits

later:
- speed ups of seedless_procrustes
- seedless prcocrustes tests
- remove outdated sign flips and procrustes from everywhere we are using 'em.

delegate to NDD?:
- (all?) tutorials
- other types of "regular" procrustes

**Comment by alyakin314** [comment]
(self-notes)
before:
2020.08.31
- [x] graspy/align/base.py
- [x] graspy/align/sign_flips.py
- [x] tests/test_sign_flips.py
- [ ] graspy/align/seedless_procrustes.py
  - backbone
  
2020.09.01
- [x] graspy/align/orthogonal_procrustes.py
- [x] tests/test_orthogonal_procrustes.py
- [x] graspy/align/seedless_procrustes.py
   - speed ups

tomorrow plan:
- tests/test_seedless_prcrustes
  - [ ] write tests for inputs
  - [ ] ask joshua for examples
  - [ ] remove outdated sign flips and procrustes from everywhere we are using 'em.
- implement other types of orthogonal procrustes

**Comment by alyakin314** [comment]
see #418 for my first attempt trying to rebase to master, and #419 for my second attempt.
i then tried to recreate here exactly what i did in #419, but github gods did not favor me.

**Comment by bdpedigo** [comment]
> see #418 for my first attempt trying to rebase to master, and #419 for my second attempt.
> i then tried to recreate here exactly what i did in #419, but github gods did not favor me.

I'm having a hard time following everything. Do you have a "clean" version of this branch anywhere, that just has your changes, and no rebases/merges?

**Comment by bdpedigo** [comment]
it looks like maybe that is this branch?

**Comment by j1c** [comment]
> see #418 for my first attempt trying to rebase to master, and #419 for my second attempt.
> i then tried to recreate here exactly what i did in #419, but github gods did not favor me.

Given your message, it might be bc you didn't pull master before rebasing? BUT, Im just not sure what the problem you were trying to solve by rebasing? are you rebasing because master is ahead of your `align-module` branch? As far as I can see, you started the branch with https://github.com/neurodata/graspy/commit/dcb70479ec326098a2c088dc5776720a181bad7a.. or is that because you rebased?

First you dont have to rebase just because master is ahead. Its only necessary if you need current changes reflected in your branch or if there were changes in master that prevents you from merging due to conflicts. Second, rebasing, in my opinion, is a pain and merging is just easier. The commits within a PR gets squashed when merged to master, so the commit history in that PR doesn't matter at all. Thats why I just merge instead of rebase.

**Comment by alyakin314** [comment]
> it looks like maybe that is this branch?

this is the one. it has one revert, but i believe that since i did it in a hacky way - it doesn't show up in the commit history,  only on github.

**Comment by alyakin314** [comment]
> > see #418 for my first attempt trying to rebase to master, and #419 for my second attempt.
> > i then tried to recreate here exactly what i did in #419, but github gods did not favor me.
> 
> Given your message, it might be bc you didn't pull master before rebasing? 

unfortunately did check that by pulling twice while being specifically on the master before doing anythign else, so this can't be the issue.

> BUT, Im just not sure what the problem you were trying to solve by rebasing? are you rebasing because master is ahead of your `align-module` branch? As far as I can see, you started the branch with [dcb7047](https://github.com/neurodata/graspy/commit/dcb70479ec326098a2c088dc5776720a181bad7a).. or is that because you rebased?

that is true but see below...

> First you dont have to rebase just because master is ahead. 

agreed (but still see below).

> Its only necessary if you need current changes reflected in your branch or if there were changes in master that prevents you from merging due to conflicts. 

correct, but: i will likely cause a conflict if i do not rebase if i do further work, because i was going to at least remove the sign flips function from the ldt and substitute it with the object from the align module, and ideally i'd want to add in seedless procrustes as well. since the ldt has been modified heavily since the time i branched, it will very likely cause conflicts and me no wants to be resolving them post-factum. unless i'll be looking at the diff from that pr while working and be very careful in not touching the same lines, but this feels like a lot of effort that can be avoided if i just rebase. in short, i'm not after [dcb7047](https://github.com/neurodata/graspy/commit/dcb70479ec326098a2c088dc5776720a181bad7a), but after #411 changes when i'm trying to rebase. alternatively i could make using align in other modules a part of a different pr.

> Second, rebasing, in my opinion, is a pain and merging is just easier. The commits within a PR gets squashed when merged to master, so the commit history in that PR doesn't matter at all. Thats why I just merge instead of rebase.

i wouldn't mind doing this, but there was something weird about the merge from master to a side branch that didn't show up right when i did that with, i think, #336 , so i decided to start doing rebases instead.

**Comment by alyakin314** [comment]
moving onto #419 since that rebase worked out correctly. will leave  this open 4 temporarily.

**Pull request closed without merging**
