### PR TITLE
Fix remove ari return value from AutoGMM.fit_predict

### LINKED ISSUE #369: remove ari return value from AutoGMM.fit_predict
Doesn't match with API well, should just get rid of this

### PR DESCRIPTION
**Pull request by caseypw**
#### Reference Issues/PRs
Fixes #369 

#### What does this implement/fix?
This removes the ari value from the data frame that is returned when running autogmm._fit_cluster. The documentation has also been changed to reflect this modification.

### CODE REVIEW

**Comment by bdpedigo** [comment]
@caseypw don't want to touch dataframe or anything in fit, just want to change return value of `fit_predict`

**Comment by caseypw** [comment]
@bdpedigo since there isn't a fit_predict function in `autogmm.py` , I originally modified the `_fit_cluster` function. I should have instead edited the `_fit_for_data` function correct?

**Comment by bdpedigo** [comment]
try checking BaseCluster

**Comment by caseypw** [comment]
How is this @bdpedigo ?

**Comment by bdpedigo** [comment]
you need to figure out why the diff is so large, should only be a few lines changed. I'm not sure what you did

**Comment by caseypw** [comment]
In `base.py`, `fit_predict` and `predict` now both only return the labels

**Comment by bdpedigo** [comment]
look under `Files changed` for this PR. Almost every line looks changed. need to fix that, only lines showing up red or green should be the ones that you changed

**Pull request closed without merging**
