### PR TITLE
save metric kwarg as attribute

### PR DESCRIPTION
**Pull request by bdpedigo**
#### What does this implement/fix? Explain your changes.
Metric kwarg should be stored as an attribute

### CODE REVIEW

**Comment by alyakin314** [comment]
i don't mind this, but i should warn you about two things:
1. this should be treated with caution because over-writing this attribute does not affect the metric used, because the test is already instantiated. unless you move the instantiation to fit, but then you either have to also carry the instantiation of the callable there, OR make it a function OR save the callable to a different variable , which brings me to ...
2. are you sure you want a string or a callable and not just a callable (i.e. whatever is passed if it is passed, or whatever we invoke from sklearn/hyppo)
to be honest, almost anything we settle on for this is messy is some way and can lead to unintuitive behaviors if the attribute is touched directly. i don't mind what you have right now. but this really should be a function.

**Comment by bdpedigo** [comment]
i think this is a problem in much of graspy, in sklearn input checking and stuff actually happens in fit. i think ideally this is where the test object would be instantiated also. i actually just tried to use an LDT object twice for two different tests and it broke for me, haven't looked into why. but something to be aware of

**Comment by alyakin314** [comment]
> i think this is a problem in much of graspy, in sklearn input checking and stuff actually happens in fit. i think ideally this is where the test object would be instantiated also. 

agreed, it probably belongs there. though i think there are some upsides to checking in init. specifically, the moment where one passes the invalid argument is often at the init, so it makes to break right away, rather than wait until fit. 

> i actually just tried to use an LDT object twice for two different tests and it broke for me, haven't looked into why. but something to be aware of

interesting. the few times i've tried it - it worked, but generally stay away from doing so. especially after we introduced hyppo back-end.

this all may be something to discuss later today.

**Comment by alyakin314** [comment]
@bdpedigo you should revert the latent distribution notebook to the one i had because i fixed a bug in it

**Comment by alyakin314** [comment]
> i actually just tried to use an LDT object twice for two different tests and it broke for me, haven't looked into why. but something to be aware of


@bdpedigo yep, i broke it by reusing as well. seems like has to do with hyppo storing the data or something else that can't be reused.

cc @sampan501 

code:
```
import numpy as np
from graspy.simulations import sbm
from graspy.inference import LatentDistributionTest

n_1 = np.random.binomial(100, 0.5)
n = [n_1, 100 - n_1]
B = [[0.9, 0.6], [0.6, 0.9]]

A1 = sbm(n, B)
A2 = sbm(n, B)

ldt = LatentDistributionTest()
ldt.fit_predict(A1, A2)
ldt.fit_predict(A1, A2)
```

full traceback:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-2216d72a3773> in <module>
      1 # there is a shortcut to fit the test and return a p-value:
----> 2 ldt.fit_predict(A1, A2)

~/Documents/Code/graspy/graspy/inference/base.py in fit_predict(self, A1, A2)
     96             The overall p value from the test
     97         """
---> 98         self.fit(A1, A2)
     99         return self.p_value_

~/Documents/Code/graspy/graspy/inference/latent_distribution_test.py in fit(self, A1, A2)
    307 
    308         data = self.test.test(
--> 309             X1_hat, X2_hat, reps=self.n_bootstraps, workers=self.workers, auto=False
    310         )
    311 

~/.virtualenvs/graphs/lib/python3.7/site-packages/hyppo/ksample/ksamp.py in test(self, reps, workers, auto, *args)
    164 
    165         if self.indep_test_name in ["dcorr", "hsic"]:
--> 166             return self.indep_test.test(u, v, reps, workers, auto=auto)
    167         else:
    168             return self.indep_test.test(u, v, reps, workers)

~/.virtualenvs/graphs/lib/python3.7/site-packages/hyppo/independence/hsic.py in test(self, x, y, reps, workers, auto)
    209 
    210         if self.is_kernel:
--> 211             check_xy_distmat(x, y)
    212 
    213         if auto and x.shape[0] > 20:

~/.virtualenvs/graphs/lib/python3.7/site-packages/hyppo/_utils.py in check_xy_distmat(x, y)
     80     if nx != px or ny != py or np.trace(x) != 0 or np.trace(y) != 0:
     81         raise ValueError(
---> 82             "Shape mismatch, x and y must be distance matrices "
     83             "have shape [n, n] and [n, n]."
     84         )

ValueError: Shape mismatch, x and y must be distance matrices have shape [n, n] and [n, n].
```

**Comment by sampan501** [comment]
Looks like a potential bug on my end. I'll put a fix for this soon

**Comment by bdpedigo** [comment]
closing for now, want to reassess when we do #375. @sampan501 whenever you ever fix the bug Anton was talking about could you just let us know please?

**Pull request closed without merging**
