### PR TITLE
Plot sorting and lcc bug fix

### PR DESCRIPTION
**Pull request by bdpedigo**
#### What does this implement/fix? Explain your changes.
 - Now plots sort by degree within block, and sort blocks by size of community membership 
 - Fixes bug for case when multigraph_lcc_intersection needs to recurse on numy array 
 - A few minor plot changes 
 - gridplot doesn't require labels

### CODE REVIEW

**Comment by j1c** [comment]
`inner_hier_labels` says `array-like`, but it implicitly assumes a numpy array (lists cant do indexing by an array of indices). So it breaks when I pass in list of labels. See below for an minimal example.

```
from graspy.simulations import sbm
from graspy.plot import heatmap

A = sbm([5, 50, 10], p=[[.5, .2, .1], 
                        [.2, .1, .3],
                        [.1, .3, .5]])

labels = ['1'] * 5 + ['2'] * 50 + ['3'] * 10

heatmap(A, inner_hier_labels=labels)
```

Same issue with `outer_hier_labels`.

**Comment by j1c** [comment]
I think either the fontsize need to be decreased, or the spacing between outer and inner labels need to be increased. So the `size` when making [new dividers](https://github.com/neurodata/graspy/blob/044a201550f4c0665387becc06828d71b579372e/graspy/plot/plot.py#L866) to like "6%" or "7%". Not sure what the right numbers are. (Maybe a more complicated solution is to try to make the background transparent)

image

```
from graspy.simulations import sbm
from graspy.plot import heatmap


A = sbm([5, 50, 10], p=[[.5, .2, .1], 
                        [.2, .1, .3],
                        [.1, .3, .5]])

labels = ['1'] * 5 + ['2'] * 50 + ['3'] * 10
outer = ['5'] * 40 + ['6'] * 25
heatmap(A, inner_hier_labels=np.array(labels), outer_hier_labels=np.array(outer))
```

**Comment by j1c** [comment]
Do you think we still need `xticklabels` and `yticklabels` for `heatmap` now that we have the bracketed labeling? These two originally existed to make plots like these:

image

but not sure if they are still necessary.

**Comment by bdpedigo** [comment]
Think I addressed the first two, I don't really have a comment on xyticklabels, I don't really see a good reason to remove it to be honest. 

Ended up making a kwarg for the hier label font size because I always end up having to change that. I made the spacing scale roughly with font size, though it could be a kwarg in itself, but I decided against that just because there is already so much. Could also make the same argument for linewidth of the brackets... It's hard to make things scale with both figure size and fontsize though, so perhaps the extra kwargs would be warranted just for getting really quality plots

**Comment by bdpedigo** [comment]
will add description for kwarg in docs after I get your thoughts on what things we should expose

**Comment by j1c** [comment]
I think the auto scaling of padding is fine. Maybe call the kwarg `hier_label_fontsize` rather than `label_fontsize` since this won't affect `xticklabels` or `yticklabels`. Thoughts?

I personally think the default figsize is big enough (its 10x10 in inches) so maybe not worth exposing linewidth of brackets.

**Pull request merged**
