### PR TITLE
Adding Signal Subgraph: vertex screening and sparse optimization

### LINKED ISSUE #120: signal subgraph
there are now 3 papers that due "signal subgraph"

- https://arxiv.org/abs/1804.09567
- https://arxiv.org/abs/1108.1427
- https://arxiv.org/abs/1801.07683v1

let's have at least some way of doing it here.

### PR DESCRIPTION
**Pull request by caseypw**
#### Reference Issues/PRs
Fixes #120 

#### What does this implement/fix? Explain your changes.
This adds iterative and non-iterative vertex screening functionality to the package.

### CODE REVIEW

**Comment by caseypw** [comment]
All pass with up to date version of Graspy directory @j1c @bdpedigo

**Comment by j1c** [comment]
Ok. Im gonna try the code a bit more, but consider it done for the class.

**Comment by caseypw** [comment]
Alright, thanks a lot @j1c 
Sorry for the late at night submission

**Comment by caseypw** [comment]
Also the proof notebook is located [here](https://github.com/NeuroDataDesign/team_graphstats1/blob/master/Casey/SS/Subgraph_Proof_Notebook.ipynb)

**Comment by caseypw** [comment]
Figured it wouldn't make sense to make an additional PR so I just added the stuff addressing https://github.com/neurodata/graspy/issues/150. There's something wrong with my hard drive right now because I thought I accidentally deleted the notebook, tutorial, etc yesterday, but I redid them today and I know I didn't delete them and now they're deleted. Also new files I make are automatically being deleted so I'm going to add to this PR as soon as possible with all of the files that I will recreate on another computer.

**Comment by caseypw** [comment]
Added fixes to #321 and #324 , not sure how to make two PRs yet

**Comment by bdpedigo** [comment]
@caseypw need you to move these new commits over to a new branch and make separate PRs

**Comment by bdpedigo** [comment]
@caseypw closing for now because looks redundant with #349 but correct me if wrong

**Pull request closed without merging**
