### PR TITLE
Revert commits from master

### PR DESCRIPTION
**Pull request by bdpedigo**
I am not sure what happened with whatever rebase/merge from master on #399 @alyakin314. 
Regardless I'd just like to revert those 2 commits and proceed from there.

### CODE REVIEW

**Comment by alyakin314** [comment]
why revert #402 tho?

**Comment by alyakin314** [comment]
as in, i see that it pops up in #399, but you won't pass the CI without it.

**Comment by alyakin314** [comment]
i believe, though not strongly convinced in, that doing merging this into master and subsequently merging #399 will have a functionally equivalent result to closing this and only merging #399, and doing this doesn't even clear up #399's diff. but if you have your reasons behind doing it this way - go ahead.

**Review by alyakin314 — APPROVED** [review]
seems fine otherwise.

**Comment by bdpedigo** [comment]
ya CI will fail now, i'll fix

**Pull request merged**
