### PR TITLE
Dimselect base

### PR DESCRIPTION
**Pull request by bvarjavand**
Still need to get testing done for the different functions, but it should at least be usable for people who want to play with it. Slack me if anything seems vague.

### CODE REVIEW

**Comment by ebridge2** [comment]
@bvarjavand I would recommend taking a look at how the baseembed class handles the dimensionality reduction, and make your model take a similar approach (ie, users pass in some arbitrary svd algorithm, and your method works with it), or at least, use the same version of `svd` that we use.

**Comment by bvarjavand** [comment]
@ebridge2 will do.

**Comment by j1c** [comment]
Update tests please.

**Comment by ebridge2** [comment]
@bvarjavand is this a work in progress for making a PR? If so, let's delete the PR for now

**Pull request closed without merging**
